[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    me-no-dev/ESPAsyncWebServer@^1.2.4
    bblanchon/ArduinoJson@^7.0.0

[env:ota]
extends = env:esp32
upload_protocol = espota
upload_port = printer.local
